# Generated by Django 4.1.2 on 2024-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_rating_avg_movie_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
