# Generated by Django 5.0.6 on 2024-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='idx',
            field=models.IntegerField(blank=True, help_text='Position IDs for ML', null=True),
        ),
    ]
